version: "3.7"
services:
    app:
        build:
            args:
                user: ppl-matkul
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: frontend-ppl-app
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - pplnetwork
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        container_name: nginx-frontend-ppl-app
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - pplnetwork

networks:
    pplnetwork:
        driver: bridge
