version: "3.7"
services:
    app:
        build:
            args:
                user: ppl-matkul
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - mynetwork
        depends_on:
            - db
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8109:80
        volumes:
            - ./:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - mynetwork
        depends_on:
            - db
            - app
    db:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: perhitungan
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: abel
        ports:
            - 3307:3306
        networks:
            - mynetwork
    phpmyadmin:
        image: phpmyadmin:latest
        restart: unless-stopped
        ports:
            - 9002:80
        environment:
            - PMA_ARBITRARY=1
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge
