# fly.toml app configuration file generated for square-apps-backend on 2023-10-13T20:27:09+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "square-apps-backend"
primary_region = "sin"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  DB_CONNECTION = "pgsql"
  DB_HOST = "https://mypgsql.fly.dev/"
  DB_DATABASE= "square_apps_backend"
  DB_PORT = 5432

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
