# fly.toml app configuration file generated for square-apps-db on 2023-10-16T20:40:50+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "square-apps-db"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  image = "mysql:8.0.32"

[env]
  MYSQL_DATABASE = "perhitungan"
  MYSQL_USER = "dyudhani"

[processes]
  app = "--datadir /data/mysql --default-authentication-plugin mysql_native_password --performance-schema=OFF --innodb-buffer-pool-size 64M"

[[mounts]]
  source = "mysqldata"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
